version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"


phases:
  install:
    commands:

      - sudo apt-get update -y
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt update
      - sudo apt install terraform
      - "terraform --version"
      - pwd
      - ls
      - $CODEBUILD_BUILD_ARN | awk -F':' '{print $6}' | awk -F'/' '{print $2}'
  #    - cd terraform 
  #   - ls
      #- cd terraformcb
      #- cd $TERRAFORM_PATH
      - terraform init
      - ls 
      - terraform validate
      #- terraform destroy --auto-approve
      - terraform plan 
      - ls
#      - aws s3 cp s3://devcwstatefile/devcwstatefile/terraform.tfstate ./
     # - ls
      - terraform apply --auto-approve
    #  - aws s3 cp ./terraform.tfstate s3://devcwstatefile/devcwstatefile/
     # - aws s3 cp s3://devcwstatefile/devcwstatefile/./terraform/dev/cloudwatchsamplescripct
    #   - aws s3 cp s3://devcwstatefile/devcwstatefile/terraform.tfstate ./
      - ls
      - pwd

  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
