version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sudo apt-get update -y
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt update
      - sudo apt install terraform
      - "terraform --version"
      - pwd
      - ls
      - terraform init
      - ls
      - terraform plan -out=FILE
      - ls
      - terraform apply --auto-approve
      - terraform apply -target=module.<sns1>


  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
