version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y python3-boto3
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.4_linux_amd64.zip
      - apt-get update
      - apt-cache search source
      - apt-get install -y curl jq
      - find /terraform -type f -print0 | xargs -0 basename -a
  build:
    commands:
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
